1.导入numpy库并简写为 np

In [1]:
import numpy as np

2.打印numpy的版本和配置说明

In [2]:
print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas

3.创建一个长度为10的空向量

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.如何找到任何一个数组的内存大小？

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


5.如何从命令行得到numpy中add函数的说明文档?

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6.创建一个长度为10并且除了第五个值为1的空向量

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7.创建一个值从10到49的向量

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8.反转一个向量(第一个元素变为最后一个)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


9.创建一个 3x3 并且值从0到8的矩阵

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10.找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


11.创建一个 3x3 的单位矩阵

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12.创建一个 3x3x3的随机数组

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.64047365 0.97748652 0.82661598]
  [0.0592023  0.37877049 0.19882099]
  [0.87828434 0.456497   0.62465404]]

 [[0.64460126 0.41175675 0.46127376]
  [0.75114325 0.97970714 0.2868818 ]
  [0.14360479 0.78697542 0.58958226]]

 [[0.54972164 0.89322674 0.52881083]
  [0.35505182 0.0709083  0.54858607]
  [0.49444636 0.43881852 0.39932248]]]


13.创建一个 10x10 的随机数组并找到它的最大值和最小值

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.020968743481428742 0.9956610086884393


14.创建一个长度为30的随机向量并找到它的平均值

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5334748033984111


15.创建一个二维数组，其中边界值为1，其余值为0

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16.对于一个已经存在的数组，如何添加一个用0填充的边界?

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17.以下表达式运行的结果分别是什么?

In [26]:
#提示: NaN = not a number, inf = infinity
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


18.创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19.创建一个8x8 的矩阵，并且设置成棋盘样式

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20.考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21.用tile函数去创建一个 8x8 的棋盘样式矩阵

In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22.对一个5x5的随机矩阵做归一化

In [22]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.8027579  0.89377412 0.33620865 0.05024269 0.33903742]
 [0.78037073 0.54252275 0.29903716 0.38612633 0.87236408]
 [0.12042129 0.50672015 0.50296104 0.         1.        ]
 [0.26042673 0.81229076 0.08252009 0.69746575 0.55320974]
 [0.85555314 0.72540718 0.78405151 0.64283177 0.3824602 ]]


23.创建一个将颜色描述为(RGBA)四个无符号整数的自定义dtype？

In [23]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

24.一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25.给定一个一维数组，对其在3到8之间的所有元素取相反数

In [25]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


26.下面脚本运行后的结果是什么?

In [27]:
print(sum(range(5),-1))

9


27.考虑一个整数向量Z,下列表达合法的是哪个?

In [31]:
Z = np.arange(5)
print(Z**Z) #legal
# print(2 << Z >> 2) # false
print(Z <- Z) # legal
print(1j*Z) # legal
# print（Z/1/1） # false
# print(Z<Z>Z ) # false

[  1   1   4  27 256]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]


28. 下列表达式的结果分别是什么?

In [32]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


29.如何从零位对浮点数组做舍入 ?

In [33]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-4.  2. -4. -9.  9.  8. -3. -1. -6. -6.]


30. 如何找到两个数组中的共同元素? 

In [34]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 4 6 8 9]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? 

In [36]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗?

In [37]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. 如何得到昨天，今天，明天的日期?

In [38]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2020-02-10
Today is 2020-02-11
Tomorrow is 2020-02-12


34. 如何得到所有与2016年7月对应的日期？

In [39]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [41]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分

In [42]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 4. 8. 1. 8. 5. 8. 1. 6. 9.]
[2. 4. 8. 1. 8. 5. 8. 1. 6. 9.]
[2. 4. 8. 1. 8. 5. 8. 1. 6. 9.]
[2 4 8 1 8 5 8 1 6 9]
[2. 4. 8. 1. 8. 5. 8. 1. 6. 9.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4

In [43]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组

In [44]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1

In [45]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序

In [46]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.0171094  0.09613449 0.13025599 0.3347261  0.40444539 0.44684195
 0.49901121 0.62157565 0.64656721 0.78494912]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？

In [47]:
Z = np.arange(10)
np.add.reduce(Z)

45

42. 对于两个随机数组A和B，检查它们是否相等

In [48]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


43. 创建一个只读数组(read-only) 

In [49]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式

In [50]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.76902689 0.84587088 1.19647673 0.82718009 0.43023593 0.76380433
 0.7172285  0.80484013 1.19545211 1.1967336 ]
[1.50924997 0.8908378  0.65943516 0.6877621  0.64539009 1.19534242
 0.6237135  0.28075989 0.92233289 0.73908729]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 

In [51]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.         0.10056393 0.11100758 0.6510074  0.85148249 0.45724614
 0.07300466 0.02814828 0.65841022 0.15794674]


46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域

In [52]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47.给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [53]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48. 打印每个numpy标量类型的最小值和最大值？

In [54]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印一个数组中的所有数值? 

In [72]:
np.set_printoptions(threshold=9999) #让threshold尽量大
Z = np.ones((16,16))
print ("全部显示：",Z)
np.set_printoptions(threshold=1) 
Z = np.ones((16,16))
print ("不全部显示：",Z)

全部显示： [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
不全部显示： [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


50. 给定标量时，如何找到数组中最接近标量的值？

In [73]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

8


51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组

In [75]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ... ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离

In [76]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.44388265 0.57542795 ... 0.05975802 0.56621892 0.38363099]
 [0.44388265 0.         0.84203965 ... 0.48537599 0.98499515 0.82195326]
 [0.57542795 0.84203965 0.         ... 0.51988547 0.42282859 0.64911367]
 ...
 [0.05975802 0.48537599 0.51988547 ... 0.         0.51171863 0.35953417]
 [0.56621892 0.98499515 0.42282859 ... 0.51171863 0.         0.36158079]
 [0.38363099 0.82195326 0.64911367 ... 0.35953417 0.36158079 0.        ]]


53. 如何将32位的浮点数(float)转换为对应的整数(integer)?

In [77]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. ... 7. 8. 9.]


54. 如何读取以下文件?

1, 2, 3, 4, 5

6,  ,  , 7, 8

 ,  , 9,10,11

In [78]:
#提示: np.genfromtxt

55. 对于numpy数组，enumerate的等价操作是什么？

In [79]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. 生成一个通用的二维Gaussian-like数组

In [80]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 ...
 [0.51979489 0.63331324 0.73444367 ... 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 ... 0.63331324 0.54610814 0.44822088]
 [0.36787944 0.44822088 0.51979489 ... 0.51979489 0.44822088 0.36787944]]


57. 对一个二维数组，如何在其内部随机放置p个元素?

In [83]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
np.set_printoptions(threshold=9999)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. 减去一个矩阵中的每一行的平均值

In [84]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.1438921  -0.01200385  0.04752908 -0.34120203 -0.22774555  0.33573202
   0.25851514  0.50229751 -0.37580462 -0.04342561]
 [-0.01636228 -0.32133646 -0.06343906  0.18680834 -0.27416762 -0.37450152
   0.35678805  0.55767381 -0.08404707  0.03258381]
 [ 0.10984368  0.13573951 -0.25043929  0.50198585 -0.40797142  0.03182683
   0.26549852  0.37973291 -0.38753118 -0.37868541]
 [ 0.11012268  0.12182977  0.41019816  0.15366059 -0.36700732  0.05528423
  -0.08045221 -0.49243063 -0.22669954  0.31549426]
 [ 0.16950746 -0.26242739  0.32785995 -0.01564899  0.06106677 -0.38969853
   0.41350278  0.2770513  -0.43675044 -0.14446291]]


59. 如何通过第n列对一个数组进行排序?

In [85]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[5 0 2]
 [3 3 3]
 [0 2 3]]
[[5 0 2]
 [0 2 3]
 [3 3 3]]


60. 如何检查一个二维数组是否有空列？

In [86]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


61. 从数组中的给定值中找出最近的值 

In [87]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.4142170412468533


62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?

In [88]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. 创建一个具有name属性的数组类

In [89]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?

In [90]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 2. 3. 2. 2. 4. 2. 4. 3.]


65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)

In [91]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量

In [92]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？

In [94]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[71 49 52 55]
 [71 52 70 45]
 [38 39 45 50]]


68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？

In [95]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.53359145 0.41069299 0.48724101 0.34857352 0.61835854 0.512014
 0.42679462 0.46765892 0.44610944 0.344357  ]


69. 如何获得点积 dot prodcut的对角线?

In [96]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))
# Fast version
np.sum(A * B.T, axis=1)
# Faster version
np.einsum("ij,ji->i", A, B)

array([0.90297334, 1.16141234, 2.1948032 , 1.59119601, 1.64039543])

70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？

In [97]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？

In [98]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. 如何对一个数组中任意两行做交换?

In [100]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print (A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [101]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 39) ( 0, 74) ( 1,  5) ( 1, 13) ( 2, 11) ( 2, 20) ( 5, 13) ( 6, 70)
 ( 6, 79) (11, 16) (11, 20) (11, 83) (16, 28) (16, 52) (16, 83) (20, 34)
 (20, 77) (28, 52) (34, 77) (39, 74) (40, 74) (40, 79) (41, 82) (41, 84)
 (69, 70) (69, 84) (70, 79) (70, 84) (74, 79) (82, 84)]


74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C

In [102]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


75. 如何通过滑动窗口计算一个数组的平均数?

In [103]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [104]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？

In [105]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？

In [106]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[12.15719063  0.07725509  3.90746703  9.42418513  7.04795105 10.98256358
  8.70426255  9.27195809  6.19748999 18.60921875]


79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？

In [107]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[6.70286232e+00 4.48981453e-01 1.22996151e+01 1.59913677e+00
  3.64633012e+00 3.26760498e-01 8.57762450e+00 8.45506010e+00
  5.04468509e+00 4.19594279e+00]
 [8.91069024e-01 2.59397730e+00 3.75256242e-01 6.33622049e-01
  6.30093358e+00 7.48386496e+00 7.94250778e+00 7.58232677e+00
  1.19777451e+01 1.05767858e+01]
 [1.36100835e+00 2.67479054e+00 7.46885830e+00 5.29104769e+00
  9.75341444e+00 9.17773048e+00 9.04854172e-01 1.22110776e+01
  7.92017055e+00 3.34169729e+00]
 [6.36057432e+00 4.35871452e+00 3.18849807e+00 2.06951205e+00
  2.06279549e+00 1.52318925e+00 2.04235373e+00 4.83826710e+00
  3.60541795e+00 5.97679035e+00]
 [8.76464756e+00 1.11564675e+00 1.17261163e+01 1.21668362e-01
  1.71063302e+00 1.76959851e+00 8.92716666e+00 6.72784231e+00
  6.71466675e+00 4.12228643e+00]
 [1.19720590e+01 2.86916320e+00 1.20702465e+01 2.26761883e+00
  1.04482716e+00 5.14472395e+00 1.08892663e+01 4.56509538e+00
  1.04369383e+01 5.37541368e+00]
 [1.48470945e+01 1.05124614e+01 1.34828040e+00 8.92901525e

80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

In [108]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[0 2 7 8 3 8 2 9 6 2]
 [7 3 1 0 1 9 1 6 8 3]
 [5 8 1 6 3 9 4 1 2 0]
 [3 9 4 8 5 2 1 8 7 2]
 [0 6 9 2 8 8 5 3 1 4]
 [3 4 7 6 8 6 8 4 6 9]
 [5 6 4 4 3 1 5 5 1 6]
 [1 9 2 4 8 6 3 0 3 1]
 [2 5 3 6 0 8 5 4 9 9]
 [6 9 3 3 9 8 1 3 8 0]]
[[0 0 0 0 0]
 [0 0 2 7 8]
 [0 7 3 1 0]
 [0 5 8 1 6]
 [0 3 9 4 8]]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?

In [109]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩

In [110]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


83. 如何找到一个数组中出现频率最高的值？

In [111]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

6


84. 从一个10x10的矩阵中提取出连续的3x3区块

In [112]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 1 1]
   [3 3 0]
   [0 0 0]]

  [[1 1 2]
   [3 0 3]
   [0 0 1]]

  [[1 2 0]
   [0 3 4]
   [0 1 3]]

  [[2 0 4]
   [3 4 2]
   [1 3 1]]

  [[0 4 2]
   [4 2 2]
   [3 1 4]]

  [[4 2 1]
   [2 2 1]
   [1 4 3]]

  [[2 1 4]
   [2 1 2]
   [4 3 3]]

  [[1 4 3]
   [1 2 0]
   [3 3 2]]]


 [[[3 3 0]
   [0 0 0]
   [1 0 3]]

  [[3 0 3]
   [0 0 1]
   [0 3 2]]

  [[0 3 4]
   [0 1 3]
   [3 2 3]]

  [[3 4 2]
   [1 3 1]
   [2 3 3]]

  [[4 2 2]
   [3 1 4]
   [3 3 3]]

  [[2 2 1]
   [1 4 3]
   [3 3 2]]

  [[2 1 2]
   [4 3 3]
   [3 2 1]]

  [[1 2 0]
   [3 3 2]
   [2 1 4]]]


 [[[0 0 0]
   [1 0 3]
   [4 1 1]]

  [[0 0 1]
   [0 3 2]
   [1 1 1]]

  [[0 1 3]
   [3 2 3]
   [1 1 0]]

  [[1 3 1]
   [2 3 3]
   [1 0 0]]

  [[3 1 4]
   [3 3 3]
   [0 0 1]]

  [[1 4 3]
   [3 3 2]
   [0 1 0]]

  [[4 3 3]
   [3 2 1]
   [1 0 3]]

  [[3 3 2]
   [2 1 4]
   [0 3 1]]]


 [[[1 0 3]
   [4 1 1]
   [3 1 0]]

  [[0 3 2]
   [1 1 1]
   [1 0 3]]

  [[3 2 3]
   [1 1 0]
   [0 3 2]]

  [[2 3 3]
   [1 0 0]
   [3 2 2]]

  [[3 3 3]
   

85. 创建一个满足 Z[i,j] == Z[j,i]的子类

In [114]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 9 10  9 11  6]
 [10  6  7  8  4]
 [ 9  7  7 42  0]
 [11  8 42  0 11]
 [ 6  4  0 11  0]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？

In [115]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)?

In [116]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. 如何利用numpy数组实现Game of Life? 

In [117]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0
  0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0
  0 1 0 1 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0
  0 1 0 0 0 0 1 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0
  0 0 0 0 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1

89. 如何找到一个数组的第n个最大值? 

In [118]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])\
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9995 9997 9996]


90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)

In [119]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. 如何从一个正常数组创建记录数组(record array)? 

In [120]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. 考虑一个大向量Z, 用两种不同的方法计算它的立方

In [123]:
x = np.random.rand()
np.power(x,3)
# 方法2
x*x*x

0.017426659075580248

93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？

In [124]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[6]


94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])

In [125]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[1 0 2]
 [1 0 1]
 [0 0 2]
 [2 2 3]
 [3 3 0]
 [2 3 1]
 [0 0 3]
 [3 0 3]
 [1 2 1]
 [1 4 3]]
[[1 0 2]
 [1 0 1]
 [0 0 2]
 [2 2 3]
 [3 3 0]
 [2 3 1]
 [0 0 3]
 [3 0 3]
 [1 2 1]
 [1 4 3]]


95. 将一个整数向量转换为matrix binary的表现形式

In [126]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的(unique)行?

In [127]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数

In [128]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
5.806401957703695
A * B
[0.61086685 0.26326282 0.32457106 0.25798521 0.57948321 0.50958273
 0.29496355 0.47327232 0.2935225  0.01298437]
inner
3.620494606005322
outer
[[0.61086685 0.56334085 0.74213037 0.25841583 0.78316234 0.47464535
  0.82075044 0.41747633 0.67023246 0.52494849]
 [0.28547288 0.26326282 0.3468155  0.12076397 0.36599073 0.22181327
  0.38355656 0.1950968  0.31321586 0.24532115]
 [0.26716289 0.24637737 0.32457106 0.11301828 0.3425164  0.20758636
  0.35895558 0.18258346 0.29312647 0.22958646]
 [0.60984891 0.56240211 0.7408937  0.25798521 0.7818573  0.47385441
  0.81938276 0.41678066 0.6691156  0.52407373]
 [0.45199707 0.41683128 0.54912253 0.19120893 0.57948321 0.35120305
  0.60729567 0.30890214 0.4959233  0.38842373]
 [0.65583113 0.60480687 0.79675661 0.27743713 0.84080884 0.50958273
  0.88116369 0.44820566 0.71956649 0.56358856]
 [0.21953501 0.20245498 0.26670886 0.09287019 0.28145504 0.17057935
  0.29496355 0.15003379 0.24086998 0.18865743]
 [0.6925096  0.63863172 

98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?

In [129]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [130]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。

In [131]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.33190565  0.05980154]
